name: Deploy multi-containers project
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t vertigojt/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true vertigojt/react-test npm run test # run?

      - run: docker build -t vertigojt/multi-client ./client
      - run: docker build -t vertigojt/multi-nginx ./nginx
      - run: docker build -t vertigojt/multi-server ./server
      - run: docker build -t vertigojt/multi-worker ./worker

      - run: docker push vertigojt/multi-client
      - run: docker push vertigojt/multi-nginx
      - run: docker push vertigojt/multi-server
      - run: docker push vertigojt/multi-worker